### PR TITLE
Keep the .git directory as .git-drupal.

### PR DESCRIPTION
**Pull request by fabianx-ai**
This is necessary for some packages like views to be updated properly.

### CODE REVIEW

**Comment by douggreen** [comment]
Why does it need to be saved. Won't this will make it such that any project doing this will need to add .git-drupal to their .gitignore?

**Comment by fabianx-ai** [comment]
It would be needed yes, so maybe we store it somewhere else like in the vendor directory instead?

The problem is:

If you run a composer install if e.g. drupal/views is outdated, then composer knows it has downloaded that from GIT and tries a:

git log

which is a pretty nasty error if .git does not exist.

So we need to preserve .git directories somehow.

**Comment by douggreen** [comment]
Please update the README.md no-git-dir section. And now that I see that the .git directory is needed, I'm wondering if this option should be renamed from no-git-dir to something else, like no-git-subtree. WDYT?

**Comment by fabianx-ai** [comment]
no-git-subtree sounds great.

**Comment by fabianx-ai** [comment]
Closing per #3.

**Pull request closed without merging**
